language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - '12'
git:
  depth: 3
script:
  - npm run build
deploy:
  provider: pages
  edge: true
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: dist/spa
  target-branch: gh-pages
  commit_message: 'Deploy release ${TRAVIS_TAG}'
  on:
    branch: main